// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnuyE0PvguZiiDnBn9UCMP9qi1fAbfAD0',
    appId: '1:539104168258:web:09b0055e417ffe4aaea0db',
    messagingSenderId: '539104168258',
    projectId: 'medical-9d533',
    authDomain: 'medical-9d533.firebaseapp.com',
    storageBucket: 'medical-9d533.appspot.com',
    measurementId: 'G-Y1X47GTMN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAk5gOpt2SgPf9Y5PVdFVURSEhQAUSH04',
    appId: '1:539104168258:android:412a3bed167d231caea0db',
    messagingSenderId: '539104168258',
    projectId: 'medical-9d533',
    storageBucket: 'medical-9d533.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkUHrW2R3jhYn_HEhfEdk-doxkqkhIW4Q',
    appId: '1:539104168258:ios:e8df5f69f8dc9fc2aea0db',
    messagingSenderId: '539104168258',
    projectId: 'medical-9d533',
    storageBucket: 'medical-9d533.appspot.com',
    androidClientId: '539104168258-u2kmkmpdl1c3c8s7u8tsbhglf98go0es.apps.googleusercontent.com',
    iosClientId: '539104168258-1f70bvq2qsc9sqd9iem6bk66bjmrfs7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.medic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkUHrW2R3jhYn_HEhfEdk-doxkqkhIW4Q',
    appId: '1:539104168258:ios:44ba5604649ff38caea0db',
    messagingSenderId: '539104168258',
    projectId: 'medical-9d533',
    storageBucket: 'medical-9d533.appspot.com',
    androidClientId: '539104168258-u2kmkmpdl1c3c8s7u8tsbhglf98go0es.apps.googleusercontent.com',
    iosClientId: '539104168258-v6jvt12vktiahha0hjpnrpdil3v8l4ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.medic.RunnerTests',
  );
}
